name: Waka Readme

on:
  schedule:
    # รันทุกวันเวลา 02:00 UTC (09:00 น. เวลาไทย) ตั้งแต่วันจันทร์-ศุกร์
    - cron: "0 2 * * 1-5"
  workflow_dispatch: # เปิดให้กดรันเองได้ด้วยมือ

jobs:
  update-readme:
    name: Waka - Readme
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@v5
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "True"
          SHOW_SHORT_INFO: "True"
          SYMBOL_VERSION: "1"
          LOCALE: "en"
